// Every interface string in four languages: English, Русский, 中文 (简体), Bahasa Melayu.
// {name} placeholders are filled in by t(key, vars). Strings marked html may contain simple markup.
export const STR = {
  // ---------------------------------------------------------------- title
  kicker: { en: 'A tiny 3D platformer', ru: 'Маленький 3D-платформер', zh: '一款迷你 3D 平台游戏', ms: 'Permainan platform 3D kecil' },
  tag: {
    en: '<em>lari</em> — Malay for <b>run</b>. Learn life lessons, unlock your powers, run from the kampung to KL.',
    ru: '<em>lari</em> по-малайски — <b>«беги»</b>. Узнавай жизненные уроки, открывай способности и беги из деревни в Куала-Лумпур.',
    zh: '<em>lari</em> 在马来语里是<b>“跑”</b>。学习人生道理，解锁超能力，从甘榜一路跑到吉隆坡。',
    ms: '<em>lari</em> — terus <b>lari</b>! Belajar pengajaran hidup, buka kuasa baharu dan lari dari kampung ke KL.',
  },
  play: { en: 'Play', ru: 'Играть', zh: '开始游戏', ms: 'Main' },
  shop: { en: 'Shop', ru: 'Магазин', zh: '商店', ms: 'Kedai' },
  settings: { en: 'Settings', ru: 'Настройки', zh: '设置', ms: 'Tetapan' },
  aboutDev: { en: 'About the dev', ru: 'Об авторе', zh: '关于作者', ms: 'Tentang pembangun' },
  hintKeys: {
    en: '← → move · Space jump · Shift dash · E shoot · ↓ pound · Esc pause',
    ru: '← → бег · Пробел прыжок · Shift рывок · E выстрел · ↓ удар · Esc пауза',
    zh: '← → 移动 · 空格 跳跃 · Shift 冲刺 · E 发射 · ↓ 重踏 · Esc 暂停',
    ms: '← → gerak · Space lompat · Shift pecut · E tembak · ↓ hentak · Esc jeda',
  },
  quips: {
    en: ['packing the backpack…', 'waking up the rooster…', 'watering the rainforest…', 'warming up the lava…', 'counting seashells…', 'lighting the cave lanterns…', 'switching on the KL skyline…'],
    ru: ['собираем рюкзак…', 'будим петуха…', 'поливаем джунгли…', 'разогреваем лаву…', 'считаем ракушки…', 'зажигаем фонари в пещере…', 'включаем огни Куала-Лумпура…'],
    zh: ['正在收拾背包……', '正在叫醒公鸡……', '正在给雨林浇水……', '正在加热岩浆……', '正在数贝壳……', '正在点亮山洞灯笼……', '正在点亮吉隆坡天际线……'],
    ms: ['mengemas beg…', 'mengejutkan ayam jantan…', 'menyiram hutan hujan…', 'memanaskan lava…', 'mengira kulit kerang…', 'menyalakan pelita gua…', 'menyalakan lampu KL…'],
  },
  loadFail: {
    en: 'Could not load the 3D assets. Open the game through a web server (not file://).',
    ru: 'Не удалось загрузить 3D-модели. Откройте игру через веб-сервер (не file://).',
    zh: '无法加载 3D 资源。请通过网页服务器打开游戏（不要用 file://）。',
    ms: 'Aset 3D gagal dimuatkan. Buka permainan melalui pelayan web (bukan file://).',
  },

  // ---------------------------------------------------------------- level select
  back: { en: '← Back', ru: '← Назад', zh: '← 返回', ms: '← Kembali' },
  chooseRoute: { en: 'Choose your route', ru: 'Выбери маршрут', zh: '选择路线', ms: 'Pilih laluan' },
  difficulty: { en: 'Difficulty', ru: 'Сложность', zh: '难度', ms: 'Kesukaran' },
  change: { en: 'change', ru: 'изменить', zh: '更改', ms: 'tukar' },
  levelN: { en: 'Level {n}', ru: 'Уровень {n}', zh: '第 {n} 关', ms: 'Tahap {n}' },
  learnLine: { en: 'Learn <b>{virtue}</b> → <i>{power}</i>', ru: 'Урок: <b>{virtue}</b> → <i>{power}</i>', zh: '学习<b>{virtue}</b> → <i>{power}</i>', ms: 'Belajar <b>{virtue}</b> → <i>{power}</i>' },
  lockPrev: { en: '🔒 Finish the previous level', ru: '🔒 Пройди предыдущий уровень', zh: '🔒 先通过上一关', ms: '🔒 Tamatkan tahap sebelumnya' },
  finale: { en: 'Finale', ru: 'Финал', zh: '终章', ms: 'Penamat' },
  klLine: { en: 'The city at the end of the road.', ru: 'Город в конце пути.', zh: '旅途终点的城市。', ms: 'Bandar di hujung jalan.' },
  lockAll: { en: '🔒 Clear all six levels', ru: '🔒 Пройди все шесть уровней', zh: '🔒 通过全部六关', ms: '🔒 Tamatkan keenam-enam tahap' },

  // ---------------------------------------------------------------- shop
  kedai: { en: 'Kedai', ru: 'Лавка', zh: '小卖部', ms: 'Kedai' },
  tabChars: { en: 'Characters', ru: 'Персонажи', zh: '角色', ms: 'Watak' },
  tabHats: { en: 'Hats', ru: 'Шапки', zh: '帽子', ms: 'Topi' },
  tabTrails: { en: 'Trails', ru: 'Шлейфы', zh: '拖尾', ms: 'Jejak' },
  tabItems: { en: 'Power-ups', ru: 'Бонусы', zh: '道具', ms: 'Kuasa' },
  owned: { en: 'owned: {n}', ru: 'есть: {n}', zh: '拥有：{n}', ms: 'dimiliki: {n}' },
  trying: { en: 'Trying on', ru: 'Примерка', zh: '试穿中', ms: 'Sedang cuba' },
  tapTry: { en: 'Tap to try on', ru: 'Нажми, чтобы примерить', zh: '点击试穿', ms: 'Ketik untuk cuba' },
  equipped: { en: 'Equipped', ru: 'Надето', zh: '已装备', ms: 'Dipakai' },
  equip: { en: 'Equip', ru: 'Надеть', zh: '装备', ms: 'Pakai' },
  buy: { en: 'Buy', ru: 'Купить', zh: '购买', ms: 'Beli' },
  need: { en: 'need {n}', ru: 'не хватает {n}', zh: '还差 {n}', ms: 'perlu {n}' },
  dragHint: { en: 'drag to turn · tap to say hi', ru: 'тяни, чтобы повернуть · нажми — поздоровается', zh: '拖动旋转 · 点一下打招呼', ms: 'seret untuk pusing · ketik untuk bertegur' },

  // ---------------------------------------------------------------- settings / about
  language: { en: 'Language', ru: 'Язык', zh: '语言', ms: 'Bahasa' },
  sound: { en: 'Sound', ru: 'Звук', zh: '声音', ms: 'Bunyi' },
  soundOn: { en: 'Sound: on', ru: 'Звук: вкл', zh: '声音：开', ms: 'Bunyi: hidup' },
  soundOff: { en: 'Sound: off', ru: 'Звук: выкл', zh: '声音：关', ms: 'Bunyi: tutup' },
  progress: { en: 'Progress', ru: 'Прогресс', zh: '进度', ms: 'Kemajuan' },
  resetSave: { en: 'Reset save', ru: 'Сбросить прогресс', zh: '重置存档', ms: 'Set semula simpanan' },
  resetConfirm: { en: 'Reset all coins, purchases and progress?', ru: 'Сбросить все монеты, покупки и прогресс?', zh: '确定重置所有金币、购买记录和进度吗？', ms: 'Set semula semua syiling, pembelian dan kemajuan?' },
  done: { en: 'Done', ru: 'Готово', zh: '完成', ms: 'Selesai' },
  builtBy: { en: 'Built by', ru: 'Автор', zh: '作者', ms: 'Dibina oleh' },
  aboutLine: {
    en: 'Diploma in ICT at APU, Kuala Lumpur · front-end, 3D web and AI content.',
    ru: 'Диплом по ИКТ в APU, Куала-Лумпур · фронтенд, 3D в вебе и AI-контент.',
    zh: '吉隆坡 APU 信息与通信技术文凭 · 前端、网页 3D 与 AI 内容。',
    ms: 'Diploma ICT di APU, Kuala Lumpur · front-end, web 3D dan kandungan AI.',
  },
  fact3d: {
    en: '<b>3D</b> every model — 12 characters, 6 worlds, 20 enemies and 6 bosses — generated with Python in <b>Blender</b>',
    ru: '<b>3D</b> все модели — 12 персонажей, 6 миров, 20 врагов и 6 боссов — сгенерированы на Python в <b>Blender</b>',
    zh: '<b>3D</b> 所有模型——12 个角色、6 个世界、20 种敌人和 6 个首领——都用 Python 在 <b>Blender</b> 中生成',
    ms: '<b>3D</b> semua model — 12 watak, 6 dunia, 20 musuh dan 6 bos — dijana dengan Python dalam <b>Blender</b>',
  },
  factEngine: {
    en: '<b>Engine</b> Three.js + a hand-written platformer physics module, proven beatable headless in Node',
    ru: '<b>Движок</b> Three.js + собственная физика платформера; проходимость уровней доказана тестами в Node',
    zh: '<b>引擎</b> Three.js + 手写的平台物理模块，并在 Node 中自动验证每一关都能通过',
    ms: '<b>Enjin</b> Three.js + modul fizik platform buatan sendiri, dibuktikan boleh ditamatkan melalui ujian Node',
  },
  factSound: {
    en: '<b>Sound</b> 11 soundtracks and every effect synthesised live with the Web Audio API',
    ru: '<b>Звук</b> 11 саундтреков и все эффекты синтезируются вживую через Web Audio API',
    zh: '<b>声音</b> 11 首配乐和所有音效都由 Web Audio API 实时合成',
    ms: '<b>Bunyi</b> 11 runut bunyi dan semua kesan disintesis secara langsung dengan Web Audio API',
  },
  factDesign: {
    en: '<b>Design</b> every life lesson you learn literally becomes a power — in four languages',
    ru: '<b>Идея</b> каждый жизненный урок буквально становится способностью — на четырёх языках',
    zh: '<b>设计</b> 你学到的每一个人生道理都会变成一种能力——支持四种语言',
    ms: '<b>Reka bentuk</b> setiap pengajaran hidup menjadi kuasa sebenar — dalam empat bahasa',
  },

  // ---------------------------------------------------------------- play
  pause: { en: 'Pause', ru: 'Пауза', zh: '暂停', ms: 'Jeda' },
  levelStart: { en: '{level} · {name} · {diff}', ru: '{level} · {name} · {diff}', zh: '{level} · {name} · {diff}', ms: '{level} · {name} · {diff}' },
  gatesAhead: { en: '3 gates ahead — the 2nd teaches {virtue}', ru: 'Впереди 3 ворот — вторые научат: {virtue}', zh: '前方有 3 道关卡——第 2 道教你{virtue}', ms: '3 pintu menanti — yang ke-2 mengajar {virtue}' },
  powerups: { en: 'power-ups: {list}', ru: 'бонусы: {list}', zh: '道具：{list}', ms: 'kuasa: {list}' },
  pu_life: { en: '+1 heart', ru: '+1 сердце', zh: '+1 颗心', ms: '+1 hati' },
  pu_shield: { en: 'shield', ru: 'щит', zh: '护盾', ms: 'perisai' },
  pu_magnet: { en: 'magnet', ru: 'магнит', zh: '磁铁', ms: 'magnet' },
  pu_star: { en: 'star', ru: 'звезда', zh: '星星', ms: 'bintang' },
  checkpoint: { en: 'Checkpoint', ru: 'Чекпоинт', zh: '存档点', ms: 'Titik semak' },
  progressSaved: { en: 'progress saved', ru: 'прогресс сохранён', zh: '进度已保存', ms: 'kemajuan disimpan' },
  alreadyLearned: { en: 'Already learned ✓', ru: 'Уже знаешь ✓', zh: '已经学会了 ✓', ms: 'Sudah dipelajari ✓' },
  powerYours: { en: '{power} is yours', ru: '{power} — твоё', zh: '{power}已属于你', ms: '{power} milik anda' },
  youKnow: { en: 'you know: {topic}', ru: 'ты знаешь: {topic}', zh: '你已懂得：{topic}', ms: 'anda tahu: {topic}' },
  powerUnlocked: { en: '{power} unlocked!', ru: 'Открыто: {power}!', zh: '解锁：{power}！', ms: '{power} dibuka!' },
  gateOpened: { en: 'Gate open', ru: 'Ворота открыты', zh: '关卡已打开', ms: 'Pintu terbuka' },
  youLearned: { en: 'you learned: {topic}', ru: 'ты узнал: {topic}', zh: '你学到了：{topic}', ms: 'anda belajar: {topic}' },
  oneUp: { en: '1-UP!', ru: '1-UP!', zh: '1-UP！', ms: '1-UP!' },
  oneUpSub: { en: '+1 heart for good', ru: '+1 сердце до конца уровня', zh: '本关永久 +1 颗心', ms: '+1 hati untuk tahap ini' },
  starPower: { en: 'Star power!', ru: 'Сила звезды!', zh: '星星之力！', ms: 'Kuasa bintang!' },
  starSub: { en: 'nothing can hurt you — run!', ru: 'тебя ничто не ранит — беги!', zh: '无敌状态——快跑！', ms: 'tiada yang boleh cederakan anda — lari!' },
  bossSub: { en: 'Stomp it {n} times — watch for the jump!', ru: 'Прыгни на него {n} раза — берегись прыжка!', zh: '踩它 {n} 次——小心它的跳跃！', ms: 'Pijak {n} kali — hati-hati lompatannya!' },
  bossSpiky: { en: 'Spiky! Stomp it only after it lands and cools down', ru: 'Шипы! Прыгай на него, только когда он приземлится и остынет', zh: '有刺！等它落地冷却后再踩', ms: 'Berduri! Pijak hanya selepas ia mendarat dan sejuk' },
  bossNag: { en: 'Beat the boss to open the way', ru: 'Победи босса, чтобы пройти', zh: '打败首领才能通过', ms: 'Kalahkan bos untuk membuka jalan' },
  bossDown: { en: '{boss} defeated!', ru: '{boss} побеждён!', zh: '{boss}被打败了！', ms: '{boss} tewas!' },
  combo: { en: 'combo ×{n}', ru: 'комбо ×{n}', zh: '连击 ×{n}', ms: 'kombo ×{n}' },
  loadingWorld: { en: 'Loading the world…', ru: 'Загружаем мир…', zh: '正在加载世界……', ms: 'Memuatkan dunia…' },

  // ---------------------------------------------------------------- gates
  kickerPower: { en: 'Power gate · {virtue}', ru: 'Ворота силы · {virtue}', zh: '能力之门 · {virtue}', ms: 'Pintu kuasa · {virtue}' },
  kickerLesson: { en: 'Life gate · {topic}', ru: 'Ворота жизни · {topic}', zh: '人生之门 · {topic}', ms: 'Pintu kehidupan · {topic}' },
  tipLabel: { en: 'Tip', ru: 'Совет', zh: '小贴士', ms: 'Tip' },
  answerPrompt: { en: 'Answer to open the gate:', ru: 'Ответь, чтобы открыть ворота:', zh: '回答问题打开关卡：', ms: 'Jawab untuk membuka pintu:' },
  hintUsed: { en: 'A wise friend helped: wrong answers struck out.', ru: 'Мудрый друг помог: неверные ответы зачёркнуты.', zh: '聪明的朋友帮了忙：错误答案已划掉。', ms: 'Kawan bijak membantu: jawapan salah dipotong.' },
  correct: { en: '✓ Correct! The gate is opening…', ru: '✓ Верно! Ворота открываются…', zh: '✓ 回答正确！关卡正在打开……', ms: '✓ Betul! Pintu sedang dibuka…' },
  newPower: { en: 'New power — {power}: {how}.', ru: 'Новая способность — {power}: {how}.', zh: '新能力——{power}：{how}。', ms: 'Kuasa baharu — {power}: {how}.' },
  learned: { en: 'Learned: {topic} (+10 coins)', ru: 'Урок усвоен: {topic} (+10 монет)', zh: '学会了：{topic}（+10 金币）', ms: 'Dipelajari: {topic} (+10 syiling)' },
  timeUpHeart: { en: '⏱ Time’s up — that cost a heart. {n} left.', ru: '⏱ Время вышло — минус сердце. Осталось {n}.', zh: '⏱ 时间到——失去一颗心。还剩 {n} 颗。', ms: '⏱ Masa tamat — hilang satu hati. Tinggal {n}.' },
  wrongHeart: { en: '✗ Not quite — that cost a heart. {n} left.', ru: '✗ Не совсем — минус сердце. Осталось {n}.', zh: '✗ 不太对——失去一颗心。还剩 {n} 颗。', ms: '✗ Kurang tepat — hilang satu hati. Tinggal {n}.' },
  wrongTry: { en: '✗ Not quite — think again and try another answer.', ru: '✗ Не совсем — подумай ещё и выбери другой ответ.', zh: '✗ 不太对——再想想，换一个答案。', ms: '✗ Kurang tepat — fikir semula dan cuba jawapan lain.' },

  // ---------------------------------------------------------------- modals
  paused: { en: 'Paused', ru: 'Пауза', zh: '已暂停', ms: 'Dijeda' },
  resume: { en: 'Resume', ru: 'Продолжить', zh: '继续', ms: 'Sambung' },
  restart: { en: 'Restart level', ru: 'Начать заново', zh: '重新开始', ms: 'Mula semula' },
  quit: { en: 'Quit to route', ru: 'Выйти к маршруту', zh: '返回路线', ms: 'Keluar ke laluan' },
  levelClear: { en: 'Level clear', ru: 'Уровень пройден', zh: '过关', ms: 'Tahap selesai' },
  coinsCollected: { en: 'Coins collected', ru: 'Собрано монет', zh: '收集金币', ms: 'Syiling dikutip' },
  flagBonus: { en: 'Flag height bonus', ru: 'Бонус за высоту флага', zh: '旗杆高度奖励', ms: 'Bonus ketinggian bendera' },
  bossBonus: { en: 'Boss bonus', ru: 'Бонус за босса', zh: '首领奖励', ms: 'Bonus bos' },
  levelBonus: { en: 'Level bonus', ru: 'Бонус уровня', zh: '关卡奖励', ms: 'Bonus tahap' },
  multiplier: { en: '{diff} multiplier', ru: 'Множитель «{diff}»', zh: '{diff}倍率', ms: 'Pengganda {diff}' },
  earned: { en: 'Earned', ru: 'Заработано', zh: '获得', ms: 'Diperoleh' },
  unlockedNext: { en: 'Unlocked: {name}', ru: 'Открыто: {name}', zh: '已解锁：{name}', ms: 'Dibuka: {name}' },
  roadOpen: { en: 'The road to Kuala Lumpur is open.', ru: 'Дорога в Куала-Лумпур открыта.', zh: '通往吉隆坡的路已经打开。', ms: 'Jalan ke Kuala Lumpur sudah terbuka.' },
  route: { en: 'Route', ru: 'Маршрут', zh: '路线', ms: 'Laluan' },
  next: { en: 'Next →', ru: 'Дальше →', zh: '下一关 →', ms: 'Seterusnya →' },
  toCity: { en: 'To the city →', ru: 'В город →', zh: '进城 →', ms: 'Ke bandar →' },
  overKicker: { en: 'Game over', ru: 'Игра окончена', zh: '游戏结束', ms: 'Permainan tamat' },
  overTitle: { en: 'Out of hearts', ru: 'Сердца закончились', zh: '心用完了', ms: 'Hati sudah habis' },
  overText: {
    en: 'Coins you picked up are kept. Try again — or grab a power-up in the shop.',
    ru: 'Собранные монеты остаются у тебя. Попробуй снова — или возьми бонус в магазине.',
    zh: '捡到的金币会保留。再试一次——或者去商店买个道具。',
    ms: 'Syiling yang dikutip disimpan. Cuba lagi — atau dapatkan kuasa di kedai.',
  },
  retry: { en: 'Retry', ru: 'Ещё раз', zh: '重试', ms: 'Cuba lagi' },
  endKicker: { en: 'You made it to Kuala Lumpur', ru: 'Ты добрался до Куала-Лумпура', zh: '你到达了吉隆坡', ms: 'Anda berjaya sampai ke Kuala Lumpur' },
  endTitle: { en: 'Welcome to the city.', ru: 'Добро пожаловать в город.', zh: '欢迎来到这座城市。', ms: 'Selamat datang ke bandar.' },
  endP1: {
    en: 'Six places, six lessons: <b>persistence, focus, patience, courage, humility</b> and <b>resilience</b>. Life works the same way — one lesson at a time, each one opening the next road.',
    ru: 'Шесть мест, шесть уроков: <b>упорство, фокус, терпение, смелость, скромность</b> и <b>стойкость</b>. В жизни так же — урок за уроком, и каждый открывает следующую дорогу.',
    zh: '六个地方，六堂课：<b>坚持、专注、耐心、勇气、谦逊</b>和<b>抗逆力</b>。人生也是如此——一次学一课，每一课都打开下一条路。',
    ms: 'Enam tempat, enam pengajaran: <b>kegigihan, fokus, kesabaran, keberanian, rendah diri</b> dan <b>daya tahan</b>. Hidup juga begitu — satu pengajaran pada satu masa, setiap satu membuka jalan seterusnya.',
  },
  endP2: {
    en: 'A new city is easier with friends who are already there. Thanks for playing — I’d love to build things like this with your team.',
    ru: 'В новом городе легче, когда там уже есть друзья. Спасибо за игру — я был бы рад создавать такое вместе с вашей командой.',
    zh: '在新城市里，有已经在那里的朋友会轻松很多。感谢游玩——我很希望能和你们的团队一起做这样的作品。',
    ms: 'Bandar baharu lebih mudah bersama kawan yang sudah ada di sana. Terima kasih kerana bermain — saya ingin membina karya seperti ini bersama pasukan anda.',
  },
  replay: { en: 'Replay levels', ru: 'Переиграть уровни', zh: '重玩关卡', ms: 'Main semula' },

  // ---------------------------------------------------------------- difficulty
  diff0: { en: 'Easy', ru: 'Лёгкий', zh: '简单', ms: 'Mudah' },
  diff1: { en: 'Normal', ru: 'Обычный', zh: '普通', ms: 'Biasa' },
  diff2: { en: 'Hard', ru: 'Сложный', zh: '困难', ms: 'Sukar' },
  diff3: { en: 'Very hard', ru: 'Очень сложный', zh: '极难', ms: 'Sangat sukar' },
  diffb0: { en: 'narrow gaps · few bugs · 3 answers', ru: 'узкие пропасти · мало жуков · 3 ответа', zh: '坑更窄 · 虫子少 · 3 个选项', ms: 'jurang sempit · sedikit pepijat · 3 jawapan' },
  diffb1: { en: '×1.5 coins', ru: '×1,5 монет', zh: '金币 ×1.5', ms: '×1.5 syiling' },
  diffb2: { en: '×2 coins · more bugs · timed gates', ru: '×2 монет · больше жуков · ворота на время', zh: '金币 ×2 · 更多虫子 · 限时答题', ms: '×2 syiling · lebih pepijat · pintu bermasa' },
  diffb3: { en: '×3 coins · bug swarms · far checkpoints · 15 s', ru: '×3 монет · рои жуков · редкие чекпоинты · 15 с', zh: '金币 ×3 · 虫群 · 存档点更远 · 15 秒', ms: '×3 syiling · kawanan pepijat · titik semak jauh · 15 s' },

  // ---------------------------------------------------------------- places
  lv_village: { en: 'Night Kampung', ru: 'Ночная деревня', zh: '夜晚甘榜', ms: 'Kampung Malam' },
  lv_forest: { en: 'Rainforest', ru: 'Тропический лес', zh: '热带雨林', ms: 'Hutan Hujan' },
  lv_volcano: { en: 'Volcano', ru: 'Вулкан', zh: '火山', ms: 'Gunung Berapi' },
  lv_beach: { en: 'Sunset Beach', ru: 'Пляж на закате', zh: '夕阳海滩', ms: 'Pantai Senja' },
  lv_cave: { en: 'Limestone Caves', ru: 'Известняковые пещеры', zh: '石灰岩洞', ms: 'Gua Batu Kapur' },
  lv_kota: { en: 'KL Rooftops', ru: 'Крыши Куала-Лумпура', zh: '吉隆坡屋顶', ms: 'Bumbung KL' },
  lv_city: { en: 'Kuala Lumpur', ru: 'Куала-Лумпур', zh: '吉隆坡', ms: 'Kuala Lumpur' },

  // ---------------------------------------------------------------- virtues (power gates) and their powers
  v_persist: { en: 'Persistence', ru: 'Упорство', zh: '坚持', ms: 'Kegigihan' },
  v_focus: { en: 'Focus', ru: 'Фокус', zh: '专注', ms: 'Fokus' },
  v_patience: { en: 'Patience', ru: 'Терпение', zh: '耐心', ms: 'Kesabaran' },
  v_courage: { en: 'Courage', ru: 'Смелость', zh: '勇气', ms: 'Keberanian' },
  v_grounded: { en: 'Humility', ru: 'Скромность', zh: '谦逊', ms: 'Rendah diri' },
  v_resilience: { en: 'Resilience', ru: 'Стойкость', zh: '抗逆力', ms: 'Daya tahan' },
  pw_double: { en: 'Double jump', ru: 'Двойной прыжок', zh: '二段跳', ms: 'Lompat berganda' },
  pw_dash: { en: 'Dash', ru: 'Рывок', zh: '冲刺', ms: 'Pecutan' },
  pw_glide: { en: 'Glide', ru: 'Парение', zh: '滑翔', ms: 'Melayang' },
  pw_shoot: { en: 'Sambal shot', ru: 'Выстрел самбалом', zh: '参巴火球', ms: 'Tembakan sambal' },
  pw_pound: { en: 'Ground pound', ru: 'Удар о землю', zh: '重踏', ms: 'Hentakan bumi' },
  pw_wall: { en: 'Wall jump', ru: 'Прыжок от стены', zh: '蹬墙跳', ms: 'Lompat dinding' },
  how_double: { en: 'press jump again in the air', ru: 'нажми прыжок ещё раз в воздухе', zh: '在空中再按一次跳跃', ms: 'tekan lompat sekali lagi di udara' },
  how_dash: { en: 'Shift — or double-tap ◀ / ▶', ru: 'Shift — или двойной тап по ◀ / ▶', zh: 'Shift——或双击 ◀ / ▶', ms: 'Shift — atau ketik dua kali ◀ / ▶' },
  how_glide: { en: 'hold jump while falling', ru: 'держи прыжок во время падения', zh: '下落时按住跳跃', ms: 'tahan lompat semasa jatuh' },
  how_shoot: { en: 'E or K — or the ✹ button', ru: 'E или K — или кнопка ✹', zh: '按 E 或 K——或 ✹ 按钮', ms: 'E atau K — atau butang ✹' },
  how_pound: { en: '↓ or S in the air — or the ▼ button', ru: '↓ или S в воздухе — или кнопка ▼', zh: '在空中按 ↓ 或 S——或 ▼ 按钮', ms: '↓ atau S di udara — atau butang ▼' },
  how_wall: { en: 'slide down a wall and press jump', ru: 'скользи по стене и жми прыжок', zh: '贴墙下滑时按跳跃', ms: 'gelongsor di dinding dan tekan lompat' },

  // ---------------------------------------------------------------- lesson gate topics
  tp_friends: { en: 'Friendship', ru: 'Дружба', zh: '友谊', ms: 'Persahabatan' },
  tp_health: { en: 'Health', ru: 'Здоровье', zh: '健康', ms: 'Kesihatan' },
  tp_nature: { en: 'Nature', ru: 'Природа', zh: '大自然', ms: 'Alam semula jadi' },
  tp_money: { en: 'Money', ru: 'Деньги', zh: '理财', ms: 'Wang' },
  tp_feelings: { en: 'Feelings', ru: 'Чувства', zh: '情绪', ms: 'Perasaan' },
  tp_safety: { en: 'Safety', ru: 'Безопасность', zh: '安全', ms: 'Keselamatan' },
  tp_teamwork: { en: 'Teamwork', ru: 'Командная работа', zh: '团队合作', ms: 'Kerja berpasukan' },
  tp_food: { en: 'Food', ru: 'Питание', zh: '饮食', ms: 'Pemakanan' },
  tp_time: { en: 'Time', ru: 'Время', zh: '时间管理', ms: 'Pengurusan masa' },
  tp_learning: { en: 'Learning', ru: 'Учёба', zh: '学习', ms: 'Pembelajaran' },
  tp_kindness: { en: 'Kindness', ru: 'Доброта', zh: '善良', ms: 'Kebaikan' },
  tp_gratitude: { en: 'Gratitude', ru: 'Благодарность', zh: '感恩', ms: 'Kesyukuran' },

  // ---------------------------------------------------------------- bosses
  boss_ayam: { en: 'Raja Ayam, the Rooster King', ru: 'Раджа Аям, король петухов', zh: '公鸡王', ms: 'Raja Ayam' },
  boss_beetle: { en: 'The Giant Beetle', ru: 'Гигантский жук', zh: '巨型甲虫', ms: 'Kumbang Gergasi' },
  boss_crab: { en: 'The Magma Crab King', ru: 'Король магмовых крабов', zh: '熔岩蟹王', ms: 'Raja Ketam Magma' },
  boss_ketam: { en: 'Ketam Raksasa, the Giant Crab', ru: 'Кетам Раксаса, гигантский краб', zh: '巨蟹', ms: 'Ketam Raksasa' },
  boss_kera: { en: 'The Monkey King', ru: 'Король обезьян', zh: '猴王', ms: 'Raja Kera' },
  boss_robot: { en: 'Bot-X, the evil twin', ru: 'Бот-X, злой двойник', zh: '邪恶双胞胎 Bot-X', ms: 'Bot-X, kembar jahat' },

  // ---------------------------------------------------------------- characters: blurb + catchphrase
  chb_coder: { en: 'Hoodie, glasses, a backpack full of side projects.', ru: 'Худи, очки и рюкзак, полный пет-проектов.', zh: '连帽衫、眼镜，背包里装满业余项目。', ms: 'Hoodie, cermin mata dan beg penuh projek sampingan.' },
  say_coder: { en: 'Hello, world! Let’s run.', ru: 'Привет, мир! Погнали.', zh: '你好，世界！出发吧。', ms: 'Hello, dunia! Jom lari.' },
  chb_kucing: { en: 'The kampung cat. Lands on its feet, mostly.', ru: 'Кот из деревни. Обычно приземляется на лапы.', zh: '甘榜小猫。大多数时候四脚着地。', ms: 'Kucing kampung. Biasanya mendarat dengan kaki.' },
  say_kucing: { en: 'Meow~ I always land on my feet.', ru: 'Мяу~ Я всегда приземляюсь на лапы.', zh: '喵～我总是四脚着地。', ms: 'Meow~ Saya sentiasa mendarat dengan kaki.' },
  chb_robot: { en: 'Runs on solar power and good manners.', ru: 'Работает на солнечной энергии и хороших манерах.', zh: '靠太阳能和好礼貌运行。', ms: 'Berkuasa solar dan budi bahasa.' },
  say_robot: { en: 'BEEP BOOP. Kindness module: ON.', ru: 'БИП-БУП. Модуль доброты: ВКЛ.', zh: '哔哔啵啵。善良模块：已开启。', ms: 'BIP BUP. Modul kebaikan: HIDUP.' },
  chb_ninja: { en: 'Silent steps. Kind heart.', ru: 'Тихие шаги. Доброе сердце.', zh: '脚步无声，心地善良。', ms: 'Langkah senyap. Hati baik.' },
  say_ninja: { en: 'Silent. Fast. Always polite.', ru: 'Тихо. Быстро. Всегда вежливо.', zh: '安静，迅速，永远有礼貌。', ms: 'Senyap. Pantas. Sentiasa sopan.' },
  chb_astro: { en: 'Already halfway to the stars.', ru: 'Уже на полпути к звёздам.', zh: '已经在去星星的半路上。', ms: 'Sudah separuh jalan ke bintang.' },
  say_astro: { en: 'One small step… one giant leap!', ru: 'Маленький шаг… и огромный прыжок!', zh: '一小步……一大跃！', ms: 'Satu langkah kecil… satu lompatan besar!' },
  chb_siti: { en: 'Top of her class and captain of the netball team.', ru: 'Отличница и капитан команды по нетболу.', zh: '班上第一名，也是篮网球队队长。', ms: 'Pelajar terbaik dan kapten pasukan bola jaring.' },
  say_siti: { en: 'Hi! Ready, steady — LARI!', ru: 'Привет! На старт, внимание — LARI!', zh: '嗨！预备——LARI！', ms: 'Hai! Sedia, mula — LARI!' },
  chb_mei: { en: 'Sprinter. Never misses the morning run.', ru: 'Спринтер. Никогда не пропускает утреннюю пробежку.', zh: '短跑选手，从不错过晨跑。', ms: 'Pelari pecut. Tidak pernah terlepas larian pagi.' },
  say_mei: { en: 'Faster than the LRT!', ru: 'Быстрее, чем метро!', zh: '比轻快铁还快！', ms: 'Lebih laju daripada LRT!' },
  chb_priya: { en: 'Dancer with jasmine in her braid.', ru: 'Танцовщица с жасмином в косе.', zh: '辫子上别着茉莉花的舞者。', ms: 'Penari dengan bunga melur di tocangnya.' },
  say_priya: { en: 'Dream big, run bigger!', ru: 'Мечтай смело, беги ещё смелее!', zh: '梦想要大，跑得更远！', ms: 'Impian besar, larian lebih jauh!' },
  chb_puteri: { en: 'Inspired by the legend of the princess of Gunung Ledang.', ru: 'Вдохновлена легендой о принцессе горы Леданг.', zh: '灵感来自金山（Gunung Ledang）公主的传说。', ms: 'Diilhamkan daripada legenda Puteri Gunung Ledang.' },
  say_puteri: { en: 'A princess can save herself, thank you.', ru: 'Принцесса может спасти себя сама, спасибо.', zh: '公主可以自己拯救自己，谢谢。', ms: 'Puteri boleh selamatkan diri sendiri, terima kasih.' },
  chb_kancil: { en: 'Sang Kancil — the clever mouse-deer of Malay folk tales.', ru: 'Санг Канчиль — хитрый оленёк из малайских сказок.', zh: '鼠鹿 Sang Kancil——马来民间故事里的机灵鬼。', ms: 'Sang Kancil — si bijak dalam cerita rakyat.' },
  say_kancil: { en: 'Small, but clever — like a chili padi!', ru: 'Маленький, да удаленький!', zh: '我个子小，但很聪明！', ms: 'Kecil-kecil cili padi!' },
  chb_harimau: { en: 'The Malayan tiger. Rare, proud and fast.', ru: 'Малайский тигр. Редкий, гордый и быстрый.', zh: '马来亚虎。稀有、骄傲又迅速。', ms: 'Harimau Malaya. Jarang, megah dan pantas.' },
  say_harimau: { en: 'RAWR! Pride of Malaysia!', ru: 'Р-Р-Р! Гордость Малайзии!', zh: '嗷呜！马来西亚的骄傲！', ms: 'AUMM! Kebanggaan Malaysia!' },
  chb_kenyalang: { en: 'The rhinoceros hornbill, symbol of Sarawak.', ru: 'Птица-носорог, символ Саравака.', zh: '犀鸟，砂拉越的象征。', ms: 'Burung kenyalang, lambang negeri Sarawak.' },
  say_kenyalang: { en: 'The sky’s the limit!', ru: 'Только небо — предел!', zh: '天空才是极限！', ms: 'Langit adalah hadnya!' },

  // ---------------------------------------------------------------- cosmetics and power-ups
  hat_none: { en: 'No hat', ru: 'Без шапки', zh: '不戴帽子', ms: 'Tanpa topi' },
  hat_cap: { en: 'Snapback', ru: 'Снэпбек', zh: '棒球帽', ms: 'Topi snapback' },
  hat_party: { en: 'Party hat', ru: 'Праздничный колпак', zh: '派对帽', ms: 'Topi parti' },
  hat_bunga: { en: 'Hibiscus', ru: 'Гибискус', zh: '大红花', ms: 'Bunga raya' },
  hat_ears: { en: 'Kitty ears', ru: 'Кошачьи ушки', zh: '猫耳朵', ms: 'Telinga kucing' },
  hat_songkok: { en: 'Songkok', ru: 'Сонгкок', zh: '宋谷帽', ms: 'Songkok' },
  hat_terendak: { en: 'Terendak straw hat', ru: 'Соломенный терендак', zh: '斗笠', ms: 'Terendak' },
  hat_headphones: { en: 'Headphones', ru: 'Наушники', zh: '耳机', ms: 'Fon kepala' },
  hat_tengkolok: { en: 'Tengkolok', ru: 'Тенгколок', zh: '马来头巾冠', ms: 'Tengkolok' },
  hat_crown: { en: 'Crown', ru: 'Корона', zh: '皇冠', ms: 'Mahkota' },
  tr_none: { en: 'No trail', ru: 'Без шлейфа', zh: '无拖尾', ms: 'Tiada jejak' },
  tr_sparks: { en: 'Gold sparks', ru: 'Золотые искры', zh: '金色火花', ms: 'Percikan emas' },
  tr_neon: { en: 'Neon teal', ru: 'Неоновая бирюза', zh: '霓虹青', ms: 'Neon firus' },
  tr_sakura: { en: 'Petals', ru: 'Лепестки', zh: '花瓣', ms: 'Kelopak bunga' },
  tr_rainbow: { en: 'Rainbow', ru: 'Радуга', zh: '彩虹', ms: 'Pelangi' },
  it_life: { en: 'Extra heart', ru: 'Доп. сердце', zh: '额外的心', ms: 'Hati tambahan' },
  itb_life: { en: 'Start the next level with 4 hearts.', ru: 'Начни следующий уровень с 4 сердцами.', zh: '下一关开局有 4 颗心。', ms: 'Mulakan tahap seterusnya dengan 4 hati.' },
  it_shield: { en: 'Bug shield', ru: 'Щит от жуков', zh: '防虫护盾', ms: 'Perisai pepijat' },
  itb_shield: { en: 'Blocks the first hit.', ru: 'Блокирует первый удар.', zh: '抵挡第一次伤害。', ms: 'Menahan serangan pertama.' },
  it_magnet: { en: 'Coin magnet', ru: 'Магнит для монет', zh: '金币磁铁', ms: 'Magnet syiling' },
  itb_magnet: { en: 'Coins fly to you.', ru: 'Монеты летят к тебе.', zh: '金币会飞向你。', ms: 'Syiling terbang ke arah anda.' },
  it_hint: { en: 'Wise friend', ru: 'Мудрый друг', zh: '聪明的朋友', ms: 'Kawan bijak' },
  itb_hint: { en: 'Strikes out wrong answers at the next gate.', ru: 'Вычёркивает неверные ответы у следующих ворот.', zh: '在下一道关卡划掉错误答案。', ms: 'Memotong jawapan salah di pintu seterusnya.' },
  it_star: { en: 'Lucky star', ru: 'Счастливая звезда', zh: '幸运星', ms: 'Bintang bertuah' },
  itb_star: { en: 'Start the next level with 10 s of star power.', ru: 'Начни уровень с 10 секундами силы звезды.', zh: '下一关开局获得 10 秒星星之力。', ms: 'Mulakan tahap dengan 10 saat kuasa bintang.' },
};
